// <auto-generated />
using System;
using Chess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.Data.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20251030151441_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chess.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Chess.Data.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "board.png"
                        });
                });

            modelBuilder.Entity("Chess.Data.Models.Figure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Figures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            Color = 1,
                            Image = "wR.png",
                            PositionX = 0.0,
                            PositionY = 87.5,
                            Type = 4
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            Color = 1,
                            Image = "wN.png",
                            PositionX = 12.5,
                            PositionY = 87.5,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 1,
                            Color = 1,
                            Image = "wB.png",
                            PositionX = 25.0,
                            PositionY = 87.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 1,
                            Color = 1,
                            Image = "wQ.png",
                            PositionX = 37.5,
                            PositionY = 87.5,
                            Type = 5
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 1,
                            Color = 1,
                            Image = "wK.png",
                            PositionX = 50.0,
                            PositionY = 87.5,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            BoardId = 1,
                            Color = 1,
                            Image = "wB.png",
                            PositionX = 62.5,
                            PositionY = 87.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            BoardId = 1,
                            Color = 1,
                            Image = "wN.png",
                            PositionX = 75.0,
                            PositionY = 87.5,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            BoardId = 1,
                            Color = 1,
                            Image = "wR.png",
                            PositionX = 87.5,
                            PositionY = 87.5,
                            Type = 4
                        },
                        new
                        {
                            Id = 9,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 0.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 12.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 25.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 37.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 50.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 14,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 62.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 75.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 16,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 87.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 17,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 0.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 12.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 19,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 25.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 20,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 37.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 21,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 50.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 22,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 62.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 23,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 75.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 24,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 87.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 25,
                            BoardId = 1,
                            Color = 0,
                            Image = "bR.png",
                            PositionX = 0.0,
                            PositionY = 0.0,
                            Type = 4
                        },
                        new
                        {
                            Id = 26,
                            BoardId = 1,
                            Color = 0,
                            Image = "bN.png",
                            PositionX = 12.5,
                            PositionY = 0.0,
                            Type = 2
                        },
                        new
                        {
                            Id = 27,
                            BoardId = 1,
                            Color = 0,
                            Image = "bB.png",
                            PositionX = 25.0,
                            PositionY = 0.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            BoardId = 1,
                            Color = 0,
                            Image = "bQ.png",
                            PositionX = 37.5,
                            PositionY = 0.0,
                            Type = 5
                        },
                        new
                        {
                            Id = 29,
                            BoardId = 1,
                            Color = 0,
                            Image = "bK.png",
                            PositionX = 50.0,
                            PositionY = 0.0,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            BoardId = 1,
                            Color = 0,
                            Image = "bB.png",
                            PositionX = 62.5,
                            PositionY = 0.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            BoardId = 1,
                            Color = 0,
                            Image = "bN.png",
                            PositionX = 75.0,
                            PositionY = 0.0,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            BoardId = 1,
                            Color = 0,
                            Image = "bR.png",
                            PositionX = 87.5,
                            PositionY = 0.0,
                            Type = 4
                        });
                });

            modelBuilder.Entity("Chess.Data.Models.Square", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Squares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            Coordinate = "a8",
                            PositionX = 0.0,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            Coordinate = "b8",
                            PositionX = 12.5,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 1,
                            Coordinate = "c8",
                            PositionX = 25.0,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 1,
                            Coordinate = "d8",
                            PositionX = 37.5,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 1,
                            Coordinate = "e8",
                            PositionX = 50.0,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 6,
                            BoardId = 1,
                            Coordinate = "f8",
                            PositionX = 62.5,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 7,
                            BoardId = 1,
                            Coordinate = "g8",
                            PositionX = 75.0,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 8,
                            BoardId = 1,
                            Coordinate = "h8",
                            PositionX = 87.5,
                            PositionY = 0.0
                        },
                        new
                        {
                            Id = 9,
                            BoardId = 1,
                            Coordinate = "a7",
                            PositionX = 0.0,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 10,
                            BoardId = 1,
                            Coordinate = "b7",
                            PositionX = 12.5,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 11,
                            BoardId = 1,
                            Coordinate = "c7",
                            PositionX = 25.0,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 12,
                            BoardId = 1,
                            Coordinate = "d7",
                            PositionX = 37.5,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 13,
                            BoardId = 1,
                            Coordinate = "e7",
                            PositionX = 50.0,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 14,
                            BoardId = 1,
                            Coordinate = "f7",
                            PositionX = 62.5,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 15,
                            BoardId = 1,
                            Coordinate = "g7",
                            PositionX = 75.0,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 16,
                            BoardId = 1,
                            Coordinate = "h7",
                            PositionX = 87.5,
                            PositionY = 12.5
                        },
                        new
                        {
                            Id = 17,
                            BoardId = 1,
                            Coordinate = "a6",
                            PositionX = 0.0,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 18,
                            BoardId = 1,
                            Coordinate = "b6",
                            PositionX = 12.5,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 19,
                            BoardId = 1,
                            Coordinate = "c6",
                            PositionX = 25.0,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 20,
                            BoardId = 1,
                            Coordinate = "d6",
                            PositionX = 37.5,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 21,
                            BoardId = 1,
                            Coordinate = "e6",
                            PositionX = 50.0,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 22,
                            BoardId = 1,
                            Coordinate = "f6",
                            PositionX = 62.5,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 23,
                            BoardId = 1,
                            Coordinate = "g6",
                            PositionX = 75.0,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 24,
                            BoardId = 1,
                            Coordinate = "h6",
                            PositionX = 87.5,
                            PositionY = 25.0
                        },
                        new
                        {
                            Id = 25,
                            BoardId = 1,
                            Coordinate = "a5",
                            PositionX = 0.0,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 26,
                            BoardId = 1,
                            Coordinate = "b5",
                            PositionX = 12.5,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 27,
                            BoardId = 1,
                            Coordinate = "c5",
                            PositionX = 25.0,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 28,
                            BoardId = 1,
                            Coordinate = "d5",
                            PositionX = 37.5,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 29,
                            BoardId = 1,
                            Coordinate = "e5",
                            PositionX = 50.0,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 30,
                            BoardId = 1,
                            Coordinate = "f5",
                            PositionX = 62.5,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 31,
                            BoardId = 1,
                            Coordinate = "g5",
                            PositionX = 75.0,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 32,
                            BoardId = 1,
                            Coordinate = "h5",
                            PositionX = 87.5,
                            PositionY = 37.5
                        },
                        new
                        {
                            Id = 33,
                            BoardId = 1,
                            Coordinate = "a4",
                            PositionX = 0.0,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 34,
                            BoardId = 1,
                            Coordinate = "b4",
                            PositionX = 12.5,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 35,
                            BoardId = 1,
                            Coordinate = "c4",
                            PositionX = 25.0,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 36,
                            BoardId = 1,
                            Coordinate = "d4",
                            PositionX = 37.5,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 37,
                            BoardId = 1,
                            Coordinate = "e4",
                            PositionX = 50.0,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 38,
                            BoardId = 1,
                            Coordinate = "f4",
                            PositionX = 62.5,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 39,
                            BoardId = 1,
                            Coordinate = "g4",
                            PositionX = 75.0,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 40,
                            BoardId = 1,
                            Coordinate = "h4",
                            PositionX = 87.5,
                            PositionY = 50.0
                        },
                        new
                        {
                            Id = 41,
                            BoardId = 1,
                            Coordinate = "a3",
                            PositionX = 0.0,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 42,
                            BoardId = 1,
                            Coordinate = "b3",
                            PositionX = 12.5,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 43,
                            BoardId = 1,
                            Coordinate = "c3",
                            PositionX = 25.0,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 44,
                            BoardId = 1,
                            Coordinate = "d3",
                            PositionX = 37.5,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 45,
                            BoardId = 1,
                            Coordinate = "e3",
                            PositionX = 50.0,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 46,
                            BoardId = 1,
                            Coordinate = "f3",
                            PositionX = 62.5,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 47,
                            BoardId = 1,
                            Coordinate = "g3",
                            PositionX = 75.0,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 48,
                            BoardId = 1,
                            Coordinate = "h3",
                            PositionX = 87.5,
                            PositionY = 62.5
                        },
                        new
                        {
                            Id = 49,
                            BoardId = 1,
                            Coordinate = "a2",
                            PositionX = 0.0,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 50,
                            BoardId = 1,
                            Coordinate = "b2",
                            PositionX = 12.5,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 51,
                            BoardId = 1,
                            Coordinate = "c2",
                            PositionX = 25.0,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 52,
                            BoardId = 1,
                            Coordinate = "d2",
                            PositionX = 37.5,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 53,
                            BoardId = 1,
                            Coordinate = "e2",
                            PositionX = 50.0,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 54,
                            BoardId = 1,
                            Coordinate = "f2",
                            PositionX = 62.5,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 55,
                            BoardId = 1,
                            Coordinate = "g2",
                            PositionX = 75.0,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 56,
                            BoardId = 1,
                            Coordinate = "h2",
                            PositionX = 87.5,
                            PositionY = 75.0
                        },
                        new
                        {
                            Id = 57,
                            BoardId = 1,
                            Coordinate = "a1",
                            PositionX = 0.0,
                            PositionY = 87.5
                        },
                        new
                        {
                            Id = 58,
                            BoardId = 1,
                            Coordinate = "b1",
                            PositionX = 12.5,
                            PositionY = 87.5
                        },
                        new
                        {
                            Id = 59,
                            BoardId = 1,
                            Coordinate = "c1",
                            PositionX = 25.0,
                            PositionY = 87.5
                        },
                        new
                        {
                            Id = 60,
                            BoardId = 1,
                            Coordinate = "d1",
                            PositionX = 37.5,
                            PositionY = 87.5
                        },
                        new
                        {
                            Id = 61,
                            BoardId = 1,
                            Coordinate = "e1",
                            PositionX = 50.0,
                            PositionY = 87.5
                        },
                        new
                        {
                            Id = 62,
                            BoardId = 1,
                            Coordinate = "f1",
                            PositionX = 62.5,
                            PositionY = 87.5
                        },
                        new
                        {
                            Id = 63,
                            BoardId = 1,
                            Coordinate = "g1",
                            PositionX = 75.0,
                            PositionY = 87.5
                        },
                        new
                        {
                            Id = 64,
                            BoardId = 1,
                            Coordinate = "h1",
                            PositionX = 87.5,
                            PositionY = 87.5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Chess.Data.Models.Board", b =>
                {
                    b.HasOne("Chess.Data.Models.ApplicationUser", "User")
                        .WithMany("Boards")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chess.Data.Models.Figure", b =>
                {
                    b.HasOne("Chess.Data.Models.Board", "Board")
                        .WithMany("Figures")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Chess.Data.Models.Square", b =>
                {
                    b.HasOne("Chess.Data.Models.Board", "Board")
                        .WithMany("Movehistory")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chess.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("Chess.Data.Models.Board", b =>
                {
                    b.Navigation("Figures");

                    b.Navigation("Movehistory");
                });
#pragma warning restore 612, 618
        }
    }
}
