// <auto-generated />
using System;
using Chess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.Data.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chess.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Chess.Data.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "board.png"
                        });
                });

            modelBuilder.Entity("Chess.Data.Models.Figure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Figures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            Color = 1,
                            Image = "wR.png",
                            PositionX = 0.0,
                            PositionY = 87.5,
                            Type = 4
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            Color = 1,
                            Image = "wN.png",
                            PositionX = 12.5,
                            PositionY = 87.5,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 1,
                            Color = 1,
                            Image = "wB.png",
                            PositionX = 25.0,
                            PositionY = 87.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 1,
                            Color = 1,
                            Image = "wQ.png",
                            PositionX = 37.5,
                            PositionY = 87.5,
                            Type = 5
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 1,
                            Color = 1,
                            Image = "wK.png",
                            PositionX = 50.0,
                            PositionY = 87.5,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            BoardId = 1,
                            Color = 1,
                            Image = "wB.png",
                            PositionX = 62.5,
                            PositionY = 87.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            BoardId = 1,
                            Color = 1,
                            Image = "wN.png",
                            PositionX = 75.0,
                            PositionY = 87.5,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            BoardId = 1,
                            Color = 1,
                            Image = "wR.png",
                            PositionX = 87.5,
                            PositionY = 87.5,
                            Type = 4
                        },
                        new
                        {
                            Id = 9,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 0.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 12.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 25.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 37.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 50.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 14,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 62.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 75.0,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 16,
                            BoardId = 1,
                            Color = 1,
                            Image = "wP.png",
                            PositionX = 87.5,
                            PositionY = 75.0,
                            Type = 3
                        },
                        new
                        {
                            Id = 17,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 0.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 12.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 19,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 25.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 20,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 37.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 21,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 50.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 22,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 62.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 23,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 75.0,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 24,
                            BoardId = 1,
                            Color = 0,
                            Image = "bP.png",
                            PositionX = 87.5,
                            PositionY = 12.5,
                            Type = 3
                        },
                        new
                        {
                            Id = 25,
                            BoardId = 1,
                            Color = 0,
                            Image = "bR.png",
                            PositionX = 0.0,
                            PositionY = 0.0,
                            Type = 4
                        },
                        new
                        {
                            Id = 26,
                            BoardId = 1,
                            Color = 0,
                            Image = "bN.png",
                            PositionX = 12.5,
                            PositionY = 0.0,
                            Type = 2
                        },
                        new
                        {
                            Id = 27,
                            BoardId = 1,
                            Color = 0,
                            Image = "bB.png",
                            PositionX = 25.0,
                            PositionY = 0.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            BoardId = 1,
                            Color = 0,
                            Image = "bQ.png",
                            PositionX = 37.5,
                            PositionY = 0.0,
                            Type = 5
                        },
                        new
                        {
                            Id = 29,
                            BoardId = 1,
                            Color = 0,
                            Image = "bK.png",
                            PositionX = 50.0,
                            PositionY = 0.0,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            BoardId = 1,
                            Color = 0,
                            Image = "bB.png",
                            PositionX = 62.5,
                            PositionY = 0.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            BoardId = 1,
                            Color = 0,
                            Image = "bN.png",
                            PositionX = 75.0,
                            PositionY = 0.0,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            BoardId = 1,
                            Color = 0,
                            Image = "bR.png",
                            PositionX = 87.5,
                            PositionY = 0.0,
                            Type = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Chess.Data.Models.Figure", b =>
                {
                    b.HasOne("Chess.Data.Models.Board", "Board")
                        .WithMany("Figures")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Chess.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chess.Data.Models.Board", b =>
                {
                    b.Navigation("Figures");
                });
#pragma warning restore 612, 618
        }
    }
}
