// <auto-generated />
using System;
using Chess.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.Infrastructure.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20250722201836_SeedBoardntity")]
    partial class SeedBoardntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chess.Domain.Entities.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "board.png",
                            Name = "Standard Chess Board"
                        });
                });

            modelBuilder.Entity("Chess.Domain.Entities.Figure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FigureImage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoveHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Figures");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Col = 0,
                            Color = "White",
                            CurrentPosition = "A2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 101,
                            Col = 1,
                            Color = "White",
                            CurrentPosition = "B2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 102,
                            Col = 2,
                            Color = "White",
                            CurrentPosition = "C2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 103,
                            Col = 3,
                            Color = "White",
                            CurrentPosition = "D2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 104,
                            Col = 4,
                            Color = "White",
                            CurrentPosition = "E2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 105,
                            Col = 5,
                            Color = "White",
                            CurrentPosition = "F2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 106,
                            Col = 6,
                            Color = "White",
                            CurrentPosition = "G2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 107,
                            Col = 7,
                            Color = "White",
                            CurrentPosition = "H2",
                            FigureImage = "wP.png",
                            MoveHistory = "[]",
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 1,
                            Col = 0,
                            Color = "White",
                            CurrentPosition = "A1",
                            FigureImage = "wR.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 5
                        },
                        new
                        {
                            Id = 2,
                            Col = 1,
                            Color = "White",
                            CurrentPosition = "B1",
                            FigureImage = "wN.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Col = 2,
                            Color = "White",
                            CurrentPosition = "C1",
                            FigureImage = "wB.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Col = 3,
                            Color = "White",
                            CurrentPosition = "D1",
                            FigureImage = "wQ.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Col = 4,
                            Color = "White",
                            CurrentPosition = "E1",
                            FigureImage = "wK.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Col = 5,
                            Color = "White",
                            CurrentPosition = "F1",
                            FigureImage = "wB.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Col = 6,
                            Color = "White",
                            CurrentPosition = "G1",
                            FigureImage = "wN.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Col = 7,
                            Color = "White",
                            CurrentPosition = "H1",
                            FigureImage = "wR.png",
                            MoveHistory = "[]",
                            Row = 7,
                            Type = 5
                        },
                        new
                        {
                            Id = 200,
                            Col = 0,
                            Color = "Black",
                            CurrentPosition = "A7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 201,
                            Col = 1,
                            Color = "Black",
                            CurrentPosition = "B7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 202,
                            Col = 2,
                            Color = "Black",
                            CurrentPosition = "C7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 203,
                            Col = 3,
                            Color = "Black",
                            CurrentPosition = "D7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 204,
                            Col = 4,
                            Color = "Black",
                            CurrentPosition = "E7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 205,
                            Col = 5,
                            Color = "Black",
                            CurrentPosition = "F7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 206,
                            Col = 6,
                            Color = "Black",
                            CurrentPosition = "G7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 207,
                            Col = 7,
                            Color = "Black",
                            CurrentPosition = "H7",
                            FigureImage = "bP.png",
                            MoveHistory = "[]",
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Col = 0,
                            Color = "Black",
                            CurrentPosition = "A8",
                            FigureImage = "bR.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 10,
                            Col = 1,
                            Color = "Black",
                            CurrentPosition = "B8",
                            FigureImage = "bN.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Col = 2,
                            Color = "Black",
                            CurrentPosition = "C8",
                            FigureImage = "bB.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Col = 3,
                            Color = "Black",
                            CurrentPosition = "D8",
                            FigureImage = "bQ.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            Col = 4,
                            Color = "Black",
                            CurrentPosition = "E8",
                            FigureImage = "bK.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 14,
                            Col = 5,
                            Color = "Black",
                            CurrentPosition = "F8",
                            FigureImage = "bB.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Col = 6,
                            Color = "Black",
                            CurrentPosition = "G8",
                            FigureImage = "bN.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Col = 7,
                            Color = "Black",
                            CurrentPosition = "H8",
                            FigureImage = "bR.png",
                            MoveHistory = "[]",
                            Row = 0,
                            Type = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
